### DISCUSSION TITLE
Slider vertical size within vertical stack

### DISCUSSION THREAD

**Discussion by dskindell** [snootched/cb-lcars#26] [Q&A] [answered]
What's the method to control the vertical size of a horizontal slider?

I noticed that if a slider is added to a vertical-stack card, it's significantly shorter.

![cb-lcars-slider-vsize](https://github.com/user-attachments/assets/04c091d6-363b-408e-898d-a7d1e0df9a60)

```
type: vertical-stack
cards:
  - type: custom:cb-lcars-multimeter-card
    enable_resize_observer: true
    variables:
      entity_match_header: true
      entity_match_slider: false
      entity_match_gauge: false
      entity_match_slider_start: false
      entity_match_slider_end: false
      _mode: slider
      _vertical: false
      _slider_mode: brightness
      card:
        border:
          left:
            size: 0
          top:
            size: 10
          right:
            size: 35
      gauge:
        sub_meter:
          show_sub_meter: true
      slider_track:
        bar_thickness: 7
        gap: 3
        bar_border_radius: 4
      entity: light.all_office_lights
      text:
        name:
          justify: flex-end
          align: right
    tap_action:
      action: toggle
    double_tap_action:
      action: more-info
    hold_action:
      action: more-info
    show_label: false
    show_name: true
    name: ALL
```

**Comment by snootched** [comment, marked as answer]
Hi there - yeah this is something that needs work for autosizing.  The easiest way to fix this is to set the `min_height` variable to the min height you want it to render as in a stack.

```yaml
variables:
  card:
    min_height: 50
```
