### DISCUSSION TITLE
How do I join a symbiont card to a host?

### DISCUSSION THREAD

**Discussion by gneely74** [snootched/cb-lcars#34] [Q&A] [answered]
What would the yaml look like to add a thermostat card to a cb lcars elbow card?

**Comment by snootched** [comment, marked as answer]
> What would the yaml look like to add a thermostat card to a cb lcars elbow card?

For basic symbiont, just paste in the yaml for the card you would like.  Basic styles usually work, but depends on the card:

![image](https://github.com/user-attachments/assets/8719ec4d-a6a5-4caf-a5e2-36d829cb7d10)

Here is the yaml for this elbow, giving it a bottom border, and squaring off the corners.

```yaml
type: custom:cb-lcars-elbow-card
cblcars_card_type: cb-lcars-header
enable_resize_observer: true
tap_action:
  action: none
double_tap_action:
  action: none
hold_action:
  action: none
variables:
  symbiont:
    enabled: true
    imprint_host: true
  card:
    border:
      top:
        size: 20
        left_radius: 0
      bottom:
        size: 20
  entity: climate.living_room
custom_fields:
  symbiont:
    card:
      type: thermostat
      entity: climate.living_room
      name: " "
      features:
        - style: icons
          type: climate-hvac-modes
        - style: icons
          type: climate-fan-modes
grid_options:
  columns: 24
  rows: 7
```
