### ISSUE TITLE
Multimeter issues

### ISSUE THREAD

**Issue by Andy1910** [snootched/cb-lcars#10]
i don't know what i am doing wrong each time i try to use the multimeter i get an error saying custom element does not exist:CBlcars-my-sliders-V2 even though my card bundle is installed and working

**Comment by snootched** [comment]
Make sure you've removed any remnants of the old version tempates from your dashboard file (ie. if you copied the previous yaml templates from github and pasted them into your dashboard.)
That custom card isn't used, and you just need the original my-slider cards from HACS.
To test - you can try the latest alpha build from here, and use on a new blank dashboard.

**Comment by adejong007** [comment]
I've been running into the same issue. It only happens with the slider mode. I'm using a new dashboard and I've refreshed the browser. HACS shows I'm using CB-LCARS v2024.12.4 and My Cards Bundle v1.0..

![image](https://github.com/user-attachments/assets/0560542d-360e-4f45-a9d4-cddbd7c69b46)

This was made using the UI, but here's the yaml.

```
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - type: custom:cb-lcars-multimeter-card
            enable_resize_observer: true
            variables:
              entity_match_header: false
              entity_match_slider: false
              entity_match_gauge: false
              entity_match_slider_start: false
              entity_match_slider_end: false
              _mode: slider
              _vertical: true
              _slider_mode: brightness
              card:
                border:
                  left:
                    size: 120
                  top:
                    size: 10
              gauge:
                sub_meter:
                  show_sub_meter: true
              entity: sensor.kitchen_temperature
            tap_action:
              action: toggle
            double_tap_action:
              action: none
            hold_action:
              action: none
            show_label: false
          - type: custom:cb-lcars-multimeter-card
            enable_resize_observer: true
            variables:
              entity_match_header: false
              entity_match_slider: false
              entity_match_gauge: false
              entity_match_slider_start: false
              entity_match_slider_end: false
              _mode: gauge
              _vertical: true
              _slider_mode: brightness
              card:
                border:
                  left:
                    size: 120
                  top:
                    size: 10
              gauge:
                sub_meter:
                  show_sub_meter: true
              entity: sensor.kitchen_temperature
            tap_action:
              action: toggle
            double_tap_action:
              action: none
            hold_action:
              action: none
            show_label: false
          - type: custom:cb-lcars-multimeter-card
            enable_resize_observer: true
            variables:
              entity_match_header: false
              entity_match_slider: false
              entity_match_gauge: false
              entity_match_slider_start: false
              entity_match_slider_end: false
              _mode: slider
              _vertical: false
              _slider_mode: brightness
              card:
                border:
                  left:
                    size: 120
                  top:
                    size: 10
              gauge:
                sub_meter:
                  show_sub_meter: true
              entity: sensor.kitchen_temperature
            tap_action:
              action: toggle
            double_tap_action:
              action: none
            hold_action:
              action: none
            show_label: false
          - type: custom:cb-lcars-multimeter-card
            enable_resize_observer: true
            variables:
              entity_match_header: false
              entity_match_slider: false
              entity_match_gauge: false
              entity_match_slider_start: false
              entity_match_slider_end: false
              _mode: gauge
              _vertical: false
              _slider_mode: brightness
              card:
                border:
                  left:
                    size: 120
                  top:
                    size: 10
              gauge:
                sub_meter:
                  show_sub_meter: true
              entity: sensor.kitchen_temperature
            tap_action:
              action: toggle
            double_tap_action:
              action: none
            hold_action:
              action: none
            show_label: false
```
