### ISSUE TITLE
Question: Sensor value in button or label? 

### ISSUE THREAD

**Issue by waynieoaks** [snootched/cb-lcars#14]
Forgive such a stupid question. 

When adding a button or label - is there a way to set an entity state or value to the label? For example the time, or temperature like in the screenshots? 

e.g. I have a Stardate sensor (sensor.stardate)

In my old markdown card, I would have 
     content: "## Stardate: {{ states('sensor.stardate')}}"

In other cards I would set entity: sensor.stardate as well as show_state: true

**Comment by waynieoaks** [comment]
Typically - once raising this issue I think I have worked it out. 

`label: "[[[ return 'Stardate: ' + states['sensor.stardate'].state; ]]]"`

However, if there is a better way to do this please do let me know - otherwise this can be closed 

(Sorry)

**Comment by snootched** [comment]
Hi there - no stupid questions btw :)

So you can get either the name or state of the entity as well.  At the moment I've written everything around `label` but all 3 are supported.  I will expose the options for `state` and `name` in the GUI editor in a future release, as I see this would be useful.

For now if you would like to show either the name or state of the entity, flip to the yaml of the card can you can replace the `label` references to `state` or `name`  All the options for the look of the text you see in the UI editor for `label` are also supported with the others.  

As an example, you can take the original `label` code:
```yaml
type: custom:cb-lcars-button-card
cblcars_card_type: cb-lcars-button-picard
show_label: true
variables:
  label: LCARS Button
  entity: light.mylight
  text:
    label:
      font_size: "14"
      font_weight: 400
```

and modify with the below to use the name or state:

```yaml
type: custom:cb-lcars-button-card
cblcars_card_type: cb-lcars-button-picard
show_name: true
variables:
  entity: light.mylight
  text:
    name:
      font_size: "14"
      font_weight: 400
```

```yaml
type: custom:cb-lcars-button-card
cblcars_card_type: cb-lcars-button-picard
show_state: true
variables:
  entity: light.mylight
  text:
    state:
      font_size: "14"
      font_weight: 400
```

you can even show all 3 on the same card, but by default they will overlap since they start with all the same settings.  I have some templates to move them around which I will expose as well.  Until then you can easily test with `label` and then flip the code to state once you are satisfied with the look.
