### ISSUE TITLE
Documentation has no info useful info on implementing hue-like card

### ISSUE THREAD

**Issue by raindropworks** [snootched/cb-lcars#25]
Like it says on the tin. Either I'm being a complete idiot, or the documentation isn't giving information on how to actually make use of the hue-like card feature once that hacs plug-in is installed.

**Comment by snootched** [comment]
Yeah sorry it's still on my todo list.. I'll get something there soon.  It's actually more of a holdover from previous version of the project.. but you can still do it...

In the meantime to get you started  (reference: https://github.com/Gh61/lovelace-hue-like-light-card?tab=readme-ov-file#api-interface)

On your dashboard, just put on a card that will provide the different entities/scenes you want to be able to call.
This is an example I put on my dashboard.  Key is to set `isVisible: false` and they won't be rendered on the dasboard, but they become available.

```yaml
type: vertical-stack
cards:
  - type: custom:hue-like-light-card
    entity: light.living_room
    scenes: null
    apiId: lcars-hue-living_room
    isVisible: false
  - type: custom:hue-like-light-card
    entity: light.kitchen
    scenes: null
    apiId: lcars-hue-kitchen
    isVisible: false
  - type: custom:hue-like-light-card
    entity: light.bathroom
    scenes: null
    apiId: lcars-hue-bathroom
    isVisible: false
  - type: custom:hue-like-light-card
    entity: light.bedroom
    scenes: null
    apiId: lcars-hue-bedroom
    isVisible: false
  - type: custom:hue-like-light-card
    entity: light.office
    scenes: null
    apiId: lcars-hue-office
    isVisible: false
  - type: custom:hue-like-light-card
    entity: light.patio
    scenes: null
    apiId: lcars-hue-patio
    isVisible: false
```

Then from your action on a button choose `navigate` and use the url such as below (or whatever you used for `apiId` key)

    tap_action:
      action: navigate
      navigation_path:  "#hue_card:lcars-hue-kitchen_openHueScreen"
