### ISSUE TITLE
Button icons not respecting sizing properties

### ISSUE THREAD

**Issue by snootched** [snootched/cb-lcars#30]
Issue: icons on buttons are not sized properly.  Height is not matching button height and the icon sizing variables are not being respected since last update.

Reported on discord (medic88)
![Image](https://github.com/user-attachments/assets/d13d2677-8b82-4237-b898-dd98b9683900)

Temporary workaround (to be fixed in next release):

-add the following style code block in the button's configuration.

```yaml
type: custom:cb-lcars-button-card
cblcars_card_type: cb-lcars-button-lozenge
show_label: true
variables:
  label: LCARS Button
  entity: light.tv
show_icon: true
styles:                                          <<-- add styles section and icon styles for height/width
  icon:
    - height: '[[[ return variables.__get_num_with_unit(variables.card.height); ]]]'
    - width: '[[[ return variables.__get_num_with_unit(variables.icon.size); ]]]'
  ```
