### ISSUE TITLE
Enhancement - add matching entity colour for buttons (similar to multimeter)

### ISSUE THREAD

**Issue by snootched** [snootched/cb-lcars#31]
Enhancement - add functonality for matching the entity colour as the button colour.  Same functionality from multimeter card.
Raised on discord (Lt. Hannah LaRouge)

Temporary: add this functionality within the button card's variables - add the below js block for returning an entity colour.

```yaml
variables:
  label: Ceaser
  entity: light.ceasar_light
  card:
    color:
      background:
        active: |
          [[[
            return variables.__get_light_css_color('light.ceaser_light') || '#ffffff'
          ]]]
        inactive: "#2f3549"
```
