### ISSUE TITLE
Enhancement - Implement new variables system and save file function

### ISSUE THREAD

**Issue by snootched** [snootched/cb-lcars#43]
Implement new global variables system for major user settings/themes.
Primarily for default colour choices, but could store other options.

For example:
```yaml
variables:
  card:
    colour:
      background:
        active: var(--cb-lcars-bg-active)
```

- `--cb-lcars-*` could be set from user-stored yaml file (in persistent directory outside of card directory)
- use `window.cblcars.themes` that's already scaffolded in
- allows for dynamic theme changes on `--cb-lcars-*` variables (code already plumbed in - just change variable names to override.. `--cb-lcars-*` instead of `--picard-*` colour values
- add custom panel to do colour settings configuration
  - add copy&paste and download as yaml button

Other user variable possibilities:
- default border widths (inherit HA-LCARS settings first which are input helpers)
- animiation defaults? (low priority)
